/*Assignment: 4
  Name: Gunjan Pravinchandra Pandya
  Part: 1*/

DROP TABLE CITY;
DROP TABLE DRIVER;

CREATE TABLE CITY
( CHAUFFERCITY VARCHAR2(20) NOT NULL,
  CHAUFFERSTATE VARCHAR2(20),
  CONSTRAINT CHAUCITY_PK PRIMARY KEY(CHAUFFERCITY)
);

CREATE TABLE DRIVER
( LICENSENUMBER INTEGER,
  RENEWED VARCHAR2(20),
  STATUS VARCHAR2(20),
  STATUSDATE DATE,
  DRIVERTYPE VARCHAR2(20),
  LICENSETYPE VARCHAR2(20),
  ORIGINALISSUEDATE DATE,
  NAME VARCHAR2(30),
  SEX VARCHAR2(10),
  CHAUFFERCITY VARCHAR2(30),
  RECORDNUMBER VARCHAR2(20) NOT NULL,
  CONSTRAINT RECNUM_PK PRIMARY KEY(RECORDNUMBER),
  CONSTRAINT CHAUCITY_FK FOREIGN KEY(CHAUFFERCITY) REFERENCES CITY(CHAUFFERCITY)
);