/*Assignment: 4
  Name: Gunjan Pravinchandra Pandya
  Part: Extra Credit*/

/*1.Query Name: Total Sales By Store/Performance of Stores
  Purpose: This query shows the total amount of dollars for all products sold in a particular store and can be used by leadership to see which stores are the best 
performing and which are the least and where they can give new offers/promotions to boost sales or to continue the offers in existing stores so as to keep the same
sales going on.*/
SELECT STOREID,SUM(NOOFITEMS*PRODUCTPRICE) AS Total_Sales 
FROM SALESTRANSACTION ST,SOLDVIA SV,PRODUCT P 
WHERE ST.TID=SV.TID AND SV.PRODUCTID=P.PRODUCTID 
GROUP BY STOREID 
ORDER BY Total_Sales DESC;

/*2.Query Name: Sold Quantity and Total Revenue Generated By Each Product/Performance of products
  Purpose: This query shows quantity sold of a particular product in all the transactions and total revenue generated by that product and leadership can see which
are the products that are in demand and which are less selling products. They can increase or decrease the price accordingly to boost the sales or make more profit.
And also they can get insight into what quantity of products to order from vendor based on the consumption.(Fast moving v/s Slow moving goods)*/
SELECT P.PRODUCTID,PRODUCTNAME,SUM(NOOFITEMS) SOLD_QUANTITY,SUM(NOOFITEMS)*PRODUCTPRICE TOTAL_REVENUE
FROM PRODUCT P,SOLDVIA SV 
WHERE P.PRODUCTID = SV.PRODUCTID 
GROUP BY P.PRODUCTID,PRODUCTNAME,PRODUCTPRICE
ORDER BY SUM(NOOFITEMS) DESC;

/*3.Query Name: Total Revenue Generated By Date
  Purpose: This query shows the total revenue generated in all the transaction across all the stores by selling all the products on a particular date. Leadership
can execute this query to see the day wise sales.*/
SELECT TDATE,SUM(NOOFITEMS*PRODUCTPRICE) TOTAL_REVENUE 
FROM SALESTRANSACTION ST, SOLDVIA SV, PRODUCT P 
WHERE ST.TID=SV.TID AND SV.PRODUCTID=P.PRODUCTID
GROUP BY TDATE ORDER BY TDATE;

/*4.Query Name: Total Items Sold and Total Amount by Region
  Purpose: This query shows the total numbers of items sold and total amount of dollar for all products sold in each region. Leadership can see in which region they
are doing good sales and where they need to improve. They can compare sales of various regions in terms of both number of items sold and dollars.*/
SELECT REGIONNAME,SUM(NOOFITEMS) ITEMS_SOLD,SUM(NOOFITEMS*PRODUCTPRICE)TOTAL_AMOUNT
FROM REGION R,STORE S,SALESTRANSACTION ST,SOLDVIA SV,PRODUCT P
WHERE R.REGIONID=S.REGIONID AND S.STOREID=ST.STOREID AND ST.TID=SV.TID AND SV.PRODUCTID=P.PRODUCTID
GROUP BY REGIONNAME;
  